export enum ActionType {
  GetOffer = 'getOffer',
  SetOffer = 'setOffer',
  ApiSetFavoriteOffer = 'ApiSetFavoriteOffer',
  ApiRemoveFavoriteOffer = 'ApiRemoveFavoriteOffer',
  GetComments = 'getComments',
  SetComments = 'setComments',
  ApiAddComment = 'apiAddComment',
  AddComment = 'addComment',
  GetNearOffers = 'getNearOffers',
  SetNearOffers = 'setNearOffers',
  ToggleHoverOffer = 'toggleHoverOffer',
  ToggleCommentsStatus = 'toggleCommentsStatus',
  ToggleOfferStatus = 'toggleOfferStatus',
  ResetNearOffersFavorites = 'resetNearOffersFavorites',
  MarkNearOffer = 'markNearOffer',
  UnMarkNearOffer = 'unMarkNearOffer',
  MarkOffer = 'markOffer',
  UnMarkOffer = 'unMarkOffer',
  ClearState = 'clearState',
}
